package systemApp;

/**
* systemApp/systemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from U:/workspace/COMP_6231_Final/src/system.idl
* Wednesday, November 28, 2018 10:19:50 PM EST
*/

public final class systemHolder implements org.omg.CORBA.portable.Streamable
{
  public systemApp.system value = null;

  public systemHolder ()
  {
  }

  public systemHolder (systemApp.system initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = systemApp.systemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    systemApp.systemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return systemApp.systemHelper.type ();
  }

}
