package systemApp;


/**
* systemApp/systemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from U:/workspace/COMP_6231_Final/src/system.idl
* Wednesday, November 28, 2018 10:19:50 PM EST
*/

public interface systemOperations 
{
  String course_availability (String command);
  String add_course (String command);
  String drop_course (String command);
  String new_course (String command);
  String delete_course (String command);
  String swap_course (String command1, String command2);
  String list_course (String command);
  String final_result ();
  void shutdown ();
} // interface systemOperations
