package systemApp;


/**
* systemApp/system.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from U:/workspace/COMP_6231_Final/src/system.idl
* Wednesday, November 28, 2018 10:19:50 PM EST
*/

public interface system extends systemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface system
