package systemApp;


/**
* systemApp/systemHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from U:/workspace/COMP_6231_A2/src/system.idl
* Monday, October 29, 2018 8:56:36 PM EDT
*/

abstract public class systemHelper
{
  private static String  _id = "IDL:systemApp/system:1.0";

  public static void insert (org.omg.CORBA.Any a, systemApp.system that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static systemApp.system extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (systemApp.systemHelper.id (), "system");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static systemApp.system read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_systemStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, systemApp.system value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static systemApp.system narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof systemApp.system)
      return (systemApp.system)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      systemApp._systemStub stub = new systemApp._systemStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static systemApp.system unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof systemApp.system)
      return (systemApp.system)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      systemApp._systemStub stub = new systemApp._systemStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
