package systemApp;


/**
* systemApp/system.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from U:/workspace/COMP_6231_A2/src/system.idl
* Monday, October 29, 2018 8:56:36 PM EDT
*/

public interface system extends systemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface system
