package systemApp;


/**
* systemApp/systemPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from U:/workspace/COMP_6231_A2/src/system.idl
* Monday, October 29, 2018 8:56:36 PM EDT
*/

public abstract class systemPOA extends org.omg.PortableServer.Servant
 implements systemApp.systemOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("course_availability", new java.lang.Integer (0));
    _methods.put ("add_course", new java.lang.Integer (1));
    _methods.put ("drop_course", new java.lang.Integer (2));
    _methods.put ("new_course", new java.lang.Integer (3));
    _methods.put ("delete_course", new java.lang.Integer (4));
    _methods.put ("swap_course", new java.lang.Integer (5));
    _methods.put ("list_course", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // systemApp/system/course_availability
       {
         String command = in.read_string ();
         String $result = null;
         $result = this.course_availability (command);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // systemApp/system/add_course
       {
         String command = in.read_string ();
         String $result = null;
         $result = this.add_course (command);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // systemApp/system/drop_course
       {
         String command = in.read_string ();
         String $result = null;
         $result = this.drop_course (command);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // systemApp/system/new_course
       {
         String command = in.read_string ();
         String $result = null;
         $result = this.new_course (command);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // systemApp/system/delete_course
       {
         String command = in.read_string ();
         String $result = null;
         $result = this.delete_course (command);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // systemApp/system/swap_course
       {
         String command1 = in.read_string ();
         String command2 = in.read_string ();
         String $result = null;
         $result = this.swap_course (command1, command2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // systemApp/system/list_course
       {
         String command = in.read_string ();
         String $result = null;
         $result = this.list_course (command);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // systemApp/system/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:systemApp/system:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public system _this() 
  {
    return systemHelper.narrow(
    super._this_object());
  }

  public system _this(org.omg.CORBA.ORB orb) 
  {
    return systemHelper.narrow(
    super._this_object(orb));
  }


} // class systemPOA
